server:
  port: 8081

spring:

  datasource:
    url: jdbc:postgresql://localhost:5430/wallet
    username: wallet
    password: wallet

  flyway:
    enabled: true
    locations:
      - db.migration
    default-schema: wallet

  jpa:
    properties:
      hibernate:
        default_schema: wallet
        format_sql: true
    show-sql: true

    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    enabled: true
  show-login-endpoint: true

